Repository JunheePark0224/Pluna, pull requests merged in 2024-12, with the labels that each got.

#28 Pages to get input data from users
  client/src/App.js
  client/src/InputData.css
  client/src/InputData.js
Labels: enhancement, help wanted

#29 Fix test bug that occurred by inserting simple test code in each test…
  client/src/tests/LogIn.test.js
  client/src/tests/SignUp.test.js
Labels: bug fixed

#37 Resolution below error
  client/src/InputData.css
  client/src/InputData.js
Labels: bug fixed

#39 Delicate development
  client/src/InputData.css
  client/src/InputData.js
Labels: enhancement

#41 details
  client/src/About.css
  client/src/About.js
  client/src/App.css
Labels: enhancement
